@echo off 
echo NOOOOOOO
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
Start http://www.google.com
pause 
exit